### ISSUE TITLE
LWP::Protocol broken by missing dependency

### ISSUE THREAD

**Issue by djgraff209** [git-for-windows/git-sdk-32#1]
Commit 7b1affd77fce5f053f94a4dee50d0cd1070ab5f6 introduced a newer version of LWP::Protocol that depends on Try::Tiny which is not in @INC() path.

Please Perl5 (usr/share/perl5/vendor_perl) to include Try::Tiny

Similar issue filed git-sdk-64 https://github.com/git-for-windows/git-sdk-64/issues/1

**Comment by dscho** [comment]
Same comment applies as to the git-for-windows/git-sdk-64#1

**Comment by dscho** [comment]
This package is now included. The next `perl-libwww` package will hopefully released soon, so the next Git for Windows version will include `Try::Tiny`, too.
